### ISSUE TITLE
Altitude/Elevation returns NaN

### ISSUE THREAD

**Issue by pinheirochagas** [dodo-saba/fit2gpx#7]
Hi, thanks a lot for this tool! 
Altitude/Elevation returns NaN both when reading fit (Strava) to df or when exporting to gpx. 
Please, find attached one of my activities. 
Thank you and best, 

Pedro
[8718041686.fit.gz](https://github.com/dodo-saba/fit2gpx/files/10069025/8718041686.fit.gz)

**Comment by dodo-saba** [comment]
Hi @pinheirochagas!

Thank you for flagging this issue. This has now been fixed in the latest version, please do let me know if it works!
I'd be delighted to know what you use the package for, so feel free to share.

As for the file you linked:
1. Impressive run!
2. Here is the GPX version with elevation (converted using the latest Converter class of the fit2gpx package): [8718041686.zip](https://github.com/dodo-saba/fit2gpx/files/10319905/8718041686.zip)

For those interested in why the issue occured:
The package was previously only extracting the 'altitude' and 'speed' fields from FIT files, however it seems certain Garmin devices (like yours) only record 'enhanced_speed' and 'enhanced_altitute' fields (which hold the same data, but in 32-bit). The package now accounts for this.

**Comment by pinheirochagas** [comment]
Thanks a lot! This is really great!
I saw that you removed the installer.
In my case, I simply replaced the fit2gpx.py on my python dir (site-packages). 
Are you working on a PIP?

**Comment by dodo-saba** [comment]
Hey @pinheirochagas 

Not sure what you are referring to (what have I removed)?
 
I've updated the package, so if you use PIP to install/update it will be fixed!
